FROM openjdk:8u282-jre
EXPOSE 8080
COPY C:\Users\amaya\git\spring-petclinic\spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar C:\Users\amaya\git\C:\Users\amaya\git\spring-petclinic\spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]